server {
    listen 80;
    server_name localhost;

    # ===========================
    # Security & CSP headers
    # ===========================
    add_header Content-Security-Policy "
      default-src 'none';
      base-uri 'self';
      object-src 'none';
      script-src 'self';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' data: https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      img-src 'self' data: blob:;
      connect-src 'self'
                  https://wz77bv68s0.execute-api.us-east-1.amazonaws.com;
      frame-ancestors 'none';
      worker-src 'self' blob:;
      media-src 'self' blob:;
      manifest-src 'self';
      form-action 'self';
      upgrade-insecure-requests;
      report-uri /csp-report
    " always;

    # Reforzadores recomendados
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;  # redundante con frame-ancestors pero ok
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;

    # ===========================
    # Angular SPA
    # ===========================
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Página de error
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    # (Opcional) cache básico de assets estáticos
    location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|webp|woff2?|ttf)$ {
        root /usr/share/nginx/html;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        try_files $uri =404;
    }

    # Bloqueos heredados / ejemplos deshabilitados
    # location ~ \.php$ { proxy_pass http://127.0.0.1; }
    # location ~ /\.ht { deny all; }
}
